-- ============================================
-- QUERY 3: Total Revenue Generated By Each Sales Rep
-- Business Question: Which sales rep generates the most revenue?
-- Tables: employees, customers, orders, orderdetails
-- Concepts: 4-table JOIN, SUM, GROUP BY
-- Finding: Gerard Hernandez leads in revenue
-- ============================================
SELECT 
    e.firstName,
    e.lastName,
    SUM(od.quantityOrdered * od.priceEach) AS total_revenue
FROM employees e                 
JOIN customers c 
    ON e.employeeNumber = c.salesRepEmployeeNumber
JOIN orders o 
    ON c.customerNumber = o.customerNumber       
JOIN orderdetails od 
    ON o.orderNumber = od.orderNumber
GROUP BY e.employeeNumber, e.firstName, e.lastName
ORDER BY total_revenue DESC
LIMIT 5;